export const AUTH_START = "AUTH_START";
export const REGISTER_SUCCESSFULL = "REGISTER_SUCCESSFULL";

export const AUTH_FAILED = "AUTH_FAILED";

export const LOGIN_SUCCESSFULL = "LOGIN_SUCCESSFULL";

export const IMAGE_UPLOADED = "IMAGE_UPLOADED";
export const IMAGE_UPLOADING = "IMAGE_UPLOADING";
export const IMAGE_UPLOADING_FAILED = "IMAGE_UPLOADING_FAILED";
