export const AUTH_START = "AUTH_START";
export const REGISTER_SUCCESSFULL = "REGISTER_SUCCESSFULL";

export const AUTH_FAILED = "AUTH_FAILED";

export const LOGIN_SUCCESSFULL = "LOGIN_SUCCESSFULL";

export const IMAGE_UPLOADED = "IMAGE_UPLOADED";
export const IMAGE_UPLOADING = "IMAGE_UPLOADING";
export const IMAGE_UPLOADING_FAILED = "IMAGE_UPLOADING_FAILED";

export const FB_USER_LOGIN = "FB_USER_LOGIN";

export const RESET_ALL_STATE = "RESET_ALL_STATE";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const SIGN_OUT = "SIGN_OUT";
export const RECOVER_DATA = "RECOVER_DATA";

export const GET_ALL_DONORS = 'GET_ALL_DONORS';
export const IS_LOADING_USER = 'IS_LOADING_USER';
export const DONOR_FORM_SUBMIT = 'DONOR_FORM_SUBMIT';
export const REQUEST_SEND = 'REQUEST_SEND';
export const EMPTY_DONOR_LIST = 'EMPTY_DONOR_LIST';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const EMPTY_NOTIFICATION = 'EMPTY_NOTIFICATION';